### ISSUE TITLE
Wrong endpoint for commands when including TZ78 device

### ISSUE THREAD

**Issue by hlehoux2021** [jeedom/plugin-zwavejs#12]
**Current Behavior**
When including the device, well recognized and commands are created in jeedom, but the commands point to endpoint 1, whereas the device tree indicates endpoint 0

**Suggested changes**
modify core/config/devices/wenzhou_280/tz78.single.switch.json to point endpoint 0

Here is the device tree:
`{
"id" : 43,
"name" : "",
"loc" : "",
"values" : {
"37-0-currentValue" : {
"id" : "43-37-0-currentValue",
"nodeId" : 43,
"toUpdate" : false,
"commandClass" : 37,
"commandClassName" : "Binary Switch",
"endpoint" : 0,
"property" : "currentValue",
"propertyName" : "currentValue",
"type" : "boolean",
"readable" : true,
"writeable" : false,
"label" : "Current value",
"stateless" : false,
"commandClassVersion" : 1,
"list" : false,
"value" : false,
"isCurrentValue" : true,
"targetValue" : "37-0-targetValue",
"lastUpdate" : 1696870693998
},
"37-0-targetValue" : {
"id" : "43-37-0-targetValue",
"nodeId" : 43,
"toUpdate" : false,
"commandClass" : 37,
"commandClassName" : "Binary Switch",
"endpoint" : 0,
"property" : "targetValue",
"propertyName" : "targetValue",
"type" : "boolean",
"readable" : true,
"writeable" : true,
"label" : "Target value",
"stateless" : false,
"commandClassVersion" : 1,
"list" : false,
"value" : false,
"lastUpdate" : 1696870692835
},
"43-0-sceneId" : {
"id" : "43-43-0-sceneId",
"nodeId" : 43,
"toUpdate" : false,
"commandClass" : 43,
"commandClassName" : "Scene Activation",
"endpoint" : 0,
"property" : "sceneId",
"propertyName" : "sceneId",
"type" : "number",
"readable" : true,
"writeable" : true,
"label" : "Scene ID",
"stateless" : false,
"commandClassVersion" : 1,
"min" : 1,
"max" : 255,
"list" : false,
"lastUpdate" : 1696870355647
},
"43-0-dimmingDuration" : {
"id" : "43-43-0-dimmingDuration",
"nodeId" : 43,
"toUpdate" : false,
"commandClass" : 43,
"commandClassName" : "Scene Activation",
"endpoint" : 0,
"property" : "dimmingDuration",
"propertyName" : "dimmingDuration",
"type" : "duration",
"readable" : true,
"writeable" : true,
"label" : "Dimming duration",
"stateless" : false,
"commandClassVersion" : 1,
"list" : false,
"value" : {
"unit" : "seconds"
},
"lastUpdate" : 1696870355648
},
"44-0-level-1" : {
"id" : "43-44-0-level-1",
"nodeId" : 43,
"toUpdate" : false,
"commandClass" : 44,
"commandClassName" : "Scene Actuator Configuration",
"endpoint" : 0,
"property" : "level",
"propertyName" : "level",
"propertyKey" : 1,
"propertyKeyName" : "1",
"type" : "number",
"readable" : true,
"writeable" : true,
"label" : "Level (1)",
"stateless" : false,
"commandClassVersion" : 1,
"min" : 0,
"max" : 255,
"list" : false,
"lastUpdate" : 1696870355648
},
"44-0-dimmingDuration-1" : {
"id" : "43-44-0-dimmingDuration-1",
"nodeId" : 43,
"toUpdate" : false,
"commandClass" : 44,
"commandClassName" : "Scene Actuator Configuration",
"endpoint" : 0,
"property" : "dimmingDuration",
"propertyName" : "dimmingDuration",
"propertyKey" : 1,
"propertyKeyName" : "1",
"type" : "duration",
"readable" : true,
"writeable" : true,
"label" : "Dimming duration (1)",
"stateless" : false,
"commandClassVersion" : 1,
"list" : false,
"value" : {
"unit" : "seconds"
},
"lastUpdate" : 1696870355648
},
`

**Comment by sarakha63** [comment]
Thx for the report, corrected in next release
